package examples
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.prop.TableDrivenPropertyChecks
import org.scalatestplus.scalacheck.ScalaCheckPropertyChecks

class MathOperationFlatspec extends AnyFlatSpec with ScalaCheckPropertyChecks:
  "Math.add" should "pass basic test" in:
    println("this is a basic test")
    assert(1 + 1 == 2)

  it should "pass bigger set of data" in:
    val testdata = Table(
      ("a", "b", "expected"),
      (1, 2, 3),
      (-1, -2, -3)
    )
    println("this is with a table")
    forAll(testdata): (a, b, expected) =>
      assert(a + b == expected)

  it should "pass random test data generated by scalacheck" in:
    forAll: (a: Int, b: Int) =>
      assert(a + b == a + b)
